services:
  master:
    image: postgres:latest
    volumes:
      - ./master/data:/var/lib/postgresql/data
      - ./create_replication_user.sql:/docker-entrypoint-initdb.d/create_replication_user.sql
    networks:
      - db-net
    env_file:
      - .env

  standby1:
    image: postgres:latest
    volumes:
      - ./standby1/data:/var/lib/postgresql/data
    networks:
      - db-net
    depends_on:
      - master
    env_file:
      - .env

  standby2:
    image: postgres:latest
    volumes:
      - ./standby2/data:/var/lib/postgresql/data
    networks:
      - db-net
    depends_on:
      - master
    env_file:
      - .env

  standby3:
    image: postgres:latest
    volumes:
      - ./standby3/data:/var/lib/postgresql/data
    networks:
      - db-net
    depends_on:
      - master
    env_file:
      - .env

networks:
  db-net:
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/24"